---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app-service
  labels:
    app: postgres-app
    author: srujana
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: postgres-app
...