---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: result-app
    author: srujana
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    app: redis-app
...