---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: voting-app
    author: srujana
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector: 
    app: voting-app
...